### ISSUE TITLE
[bug] no fallback to ipv4 for auth-zone if node's ipv6 upstream connectivity is not available

### ISSUE THREAD

**Issue by ghost** [NLnetLabs/unbound#35]
1.9.1 on OpenWrt 18.06 trunk
___
in case the node's ipv6 upstream connectivity/link is unavailable `unbound`'s upstream query traffic falls back to ipv4 and dns queries are resolved.

However, for some inexplicable reason that is not working for traffic specified via:

```
auth-zone:
  name: "."
  for-downstream: no
  fallback-enabled: yes
  zonefile: "/srv/unbound/zone files/root"
  master: e.root-servers.net
  master: d.root-servers.net
  master: c.root-servers.net
  master: b.root-servers.net
  master: k.root-servers.net
  master: g.root-servers.net
  master: f.root-servers.net
```

The `unbound` log is showing is the apparent attempts to contact the root zone servers via ipv6, which fails as expected in case the node's ipv6 upstream connectivity/link is unavailable, however it would be expected then to fallback to ipv4 instead, same as `unbound` is doing for upstream query traffic that is not specified in `auth-zone`:

> info: resolving f.root-servers.net. A IN
> info: resolving f.root-servers.net. AAAA IN
> info: resolving g.root-servers.net. A IN
> info: resolving g.root-servers.net. AAAA IN
> info: resolving k.root-servers.net. A IN
> info: resolving k.root-servers.net. AAAA IN
> info: resolving b.root-servers.net. A IN
> info: resolving b.root-servers.net. AAAA IN
> info: resolving c.root-servers.net. A IN
> info: resolving c.root-servers.net. AAAA IN
> info: resolving d.root-servers.net. A IN
> info: resolving d.root-servers.net. AAAA IN
> info: resolving e.root-servers.net. A IN
> info: resolving e.root-servers.net. AAAA IN
> notice: sendto failed: Permission denied
> notice: remote address is 2001:500:2f::f port 53
> notice: sendto failed: Permission denied
> notice: remote address is 2001:500:12::d0d port 53
> notice: sendto failed: Permission denied
> notice: remote address is 2001:7fd::1 port 53
> notice: sendto failed: Permission denied
> notice: remote address is 2001:500:200::b port 53
> notice: sendto failed: Permission denied
> notice: remote address is 2001:500:2::c port 53
> notice: sendto failed: Permission denied
> notice: remote address is 2001:500:2d::d port 53
> notice: sendto failed: Permission denied
> notice: remote address is 2001:500:a8::e port 53
___
It seems that in such case unbound is not attempting ipv4 connectivity and just gives up, even with global server setting `prefer-ip6: no`.
Only way to get it working appears to be setting `do-ip6: no`

**Comment by wcawijngaards** [comment]
This looks like the bug that was fixed in https://github.com/NLnetLabs/unbound/commit/474afc9016d34a98537a97cc94e14d329c7d8aeb .  You could update to use the latest development code.  That should fix it.  If your problem also happens with that version, it is (another) bug.

**Comment by ghost** [comment]
Will have to see whether the downstream package maintainer will patch or else will have to wait for the next production release from source and its provision at downstream

**Comment by e3k** [comment]
issue still present in unbound 1.9.6-3 on openwrt. could you be version specific and tell me which version has it fixed?

**Comment by wcawijngaards** [comment]
The commit that is referenced became part of the 1.9.2 release.  There are other fixes for the auth-zone code in the mean time but they do not seem very similar to this one.

**Comment by e3k** [comment]
my logs are full of messages like:
notice: sendto failed: Permission denied
notice: remote address is 2001:500:2::c port 53

resolving some top level domains fails for some there is no issue (.org fails a lot).
i have now turned on: "do-ip6: no" and testing it as an intermittent issue.

**Comment by ghost** [comment]
@e3k OpenWrt Master provides currently *unbound* v1.10.0, which does not exhibit the issue. Unfortunately it does does not look like of getting backported to OpenWrt current stable branch

**Comment by e3k** [comment]
ok so maybe i wait.
by the way the 'do-ip6: no' does work probably only partialy as today the first time i could not resolve forums.gentoo.org
but i could resolve gentoo.org and irc.gentoo.org during the same time span.
any thoughts about this?

**Comment by ghost** [comment]
@e3k Just checked another of my OpenWrt nodes with *unbound_1.9.6-2_arm_cortex-a9_vfpv3.ipk* installed and the ipv6 issue is not present. Maybe there is some issue with node's ipv6 upstream connectivity?

**Comment by e3k** [comment]
might be i disabled ipv6 on WAN. got to check the router.
also my issue is intermittent. every few days and affects mainly the .org domain and some others.

**Comment by in4mer** [comment]
I can confirm v1.10.0 is available using openwrt 18.06, and I have seen this problem using the previous version.  A note:  If you update unbound with opkg, make sure you also update libunbound; otherwise you'll get symbol resolution errors.

I don't know that it is helping, but I have additionally configured unbound using uci to only use ipv4, using the following:

`uci set unbound.@unbound[0].protocol=ip4_only; uci commit; /etc/init.d/unbound restart`

This changes /etc/config/unbound to set protocol, which is the key that sets "do-ip4: yes" and "do-ip6: no" in /var/lib/unbound/unbound.conf when /etc/init.d/unbound is called.

Further info:  I have ipv6 disabled across my entire network.  Also, make sure the previous version of unbound actually exits when you call restart.  I have no idea how but I had a zombie old-version unbound For Some Time that was making me nuts thinking nothing was helping.
