### ISSUE TITLE
Problem with ECS and cache

### ISSUE THREAD

**Issue by jiangzhuti** [NLnetLabs/unbound#37]
I'm using unbound 1.6.7, and recently encountered a problem.
For example, authoritative nameserver A returns a A record (11.22.33.44) to a query a.testa.com, subnet=1.2.3.4/32/0:
![unbound_1](https://user-images.githubusercontent.com/3127813/58935550-56a9da80-87a0-11e9-8b6e-adae33f4b382.png)

.. and returns a CNAME record (a.testb.com) to subnet=5.6.7.8/32/0:
![unbound_2](https://user-images.githubusercontent.com/3127813/58935558-5c9fbb80-87a0-11e9-8fac-93355dbfbf3b.png)

.. and Authoritative Nameserver B doesn't support ECS.
then within the TTL(60 seconds), a client send a query(a.testa.com, subnet=1.2.3.4/32/0) to unbound. the correct response is 11.22.33.44, but unbound replies CNAME and A 55.66.77.88 from the cache:
![unbound_3](https://user-images.githubusercontent.com/3127813/58952519-89ff6000-87c6-11e9-8ee0-273e23073cb8.png)

**Comment by jiangzhuti** [comment]
is this a bug related to ecs cache?

**Comment by jiangzhuti** [comment]
I finally find out that the reply from auth server B(ecs disabled) would be stored in the global cache, not the subnetmod cache. After that, all queries of a.testa.com will be asked using the global cached result, which is wrong.

**Comment by chantra** [comment]
cc @ralphdolmans .

@jiangzhuti, I understand that the example uses fake subnets, but just to confirm, when the issue happens, none of the client subnets are overlapping with each others, right? I would look like the issue is that when querying for a.testb.com, the whole msg is stored in the cache because it uses the subnet in the last response (e.g no ECS for testb.com) while it should use the most specific subnet ever found in the cname chain.

Also, do you have a repro that could be used by Unbound folks? like possibly some queries that could be performed against a live name server?

**Comment by ralphdolmans** [comment]
Thanks for the report. I think we use the prefix scope of the last query for the caching. Because the last query in above example is answered without ECS the whole message gets stored in the global cache, which is a bug.

I think @chantra's suggestion to use the most specific one in the chain makes sense.

**Comment by ameshkov** [comment]
Relevant thread on the mail list:
https://nlnetlabs.nl/pipermail/unbound-users/2015-May/009263.html

This kind of GeoDns is used by Amazon Route53 so we can assume this approach is widespread.

Here's a domain Unbound folks can use for testing: `video.profileedge.ru`

```
$ dig -t a video.profileedge.ru @ns-12.awsdns-01.com. +subnet=198.211.98.0/24
...
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; CLIENT-SUBNET: 198.211.98.0/24/24
...
...
;; ANSWER SECTION:
video.profileedge.ru.	3600	IN	CNAME	us.profileedge.ru.
us.profileedge.ru.	3600	IN	CNAME	sf-01.us.profileedge.ru.
sf-01.us.profileedge.ru. 3600	IN	A	138.68.197.195
...
```

> **; CLIENT-SUBNET: 198.211.98.0/24/24**

However, it is ignored by Unbound due to:
```
$ dig -t a us.profileedge.ru. @ns-12.awsdns-01.com. +subnet=198.211.98.0/24
...
...
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; CLIENT-SUBNET: 198.211.98.0/24/0
...
```

**Comment by ameshkov** [comment]
The issue is reproduced on Unbound compiled from the master branch.

**Comment by ralphdolmans** [comment]
Thanks all. This should be fixed in https://github.com/NLnetLabs/unbound/commit/99fd6cf7118389128c8016d211f1f432abcab523, which will be part of the next release.

**Comment by 395096713** [comment]
hi , i use 1.13.1 verison, i feel this problem still exist
unbound -V
Version 1.13.1
Configure line: --with-libevent=/usr/lib/libevent --enable-subnet
for example:

first request:

dig @127.0.0.1 -p 54 cache-video.iq.com +subnet=114.44.227.87

; <<>> DiG 9.11.0.1 <<>> @127.0.0.1 -p 54 cache-video.iq.com +subnet=114.44.227.87
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 1834
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; CLIENT-SUBNET: 114.44.227.87/32/12
;; QUESTION SECTION:
;cache-video.iq.com.		IN	A

;; ANSWER SECTION:
cache-video.iq.com.	600	IN	A	118.26.32.178


second request:

dig @127.0.0.1 -p 54 cache-video.iq.com +subnet=67.220.90.13

; <<>> DiG 9.11.0.1 <<>> @127.0.0.1 -p 54 cache-video.iq.com +subnet=67.220.90.13
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 32224
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; CLIENT-SUBNET: 67.220.90.13/32/0
;; QUESTION SECTION:
;cache-video.iq.com.		IN	A
;; ANSWER SECTION:
cache-video.iq.com.	304	IN	CNAME	api.iq.com.edgekey.net.
api.iq.com.edgekey.net.	20338	IN	CNAME	e36827.a.akamaiedge.net.
e36827.a.akamaiedge.net. 20	IN	A	23.56.108.81
e36827.a.akamaiedge.net. 20	IN	A	23.56.108.42

third request:

dig @127.0.0.1 -p 54 cache-video.iq.com +subnet=114.44.227.87

; <<>> DiG 9.11.0.1 <<>> @127.0.0.1 -p 54 cache-video.iq.com +subnet=114.44.227.87
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 31407
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;cache-video.iq.com.		IN	A

;; ANSWER SECTION:
cache-video.iq.com.	549	IN	CNAME	api.iq.com.edgekey.net.
api.iq.com.edgekey.net.	19924	IN	CNAME	e36827.a.akamaiedge.net.
e36827.a.akamaiedge.net. 17	IN	A	23.56.108.42
e36827.a.akamaiedge.net. 17	IN	A	23.56.108.81

subnet=114.44.227.87 request result is still coverd by  +subnet=67.220.90.13 ??
