### ISSUE TITLE
error: udp connect failed

### ISSUE THREAD

**Issue by graphine27** [NLnetLabs/unbound#431]
Hello,

I'm using 1.13.1 with OpenWrt.
The log is flooded with `error: udp connect failed: Permission denied for <ipv6 addr>`
This happens before the device gets an internet connection, after a connection is made, the log is not flooded.

I have set verbosity: 0 but still see these logs.

**Comment by graphine27** [comment]
After enabling tls_upstream for the zone the udp errors are gone but these appeared: `error: outgoing tcp: connect: Permission denied for 2606:4700:4700::1111 port 853`
These errors occur less often than udp ones did.

**Comment by wcawijngaards** [comment]
Thanks for the bug report.  The first, udp connect, error is fixed in the commit.  It now appears only at high verbosity.  The second one is strange because it should only appear at verbosity 2 and higher.  Changed the code to make that 4 and higher.

**Comment by ndilieto** [comment]
https://github.com/NLnetLabs/unbound/commit/40fbc3fa8a802dc3d9f12ee6db8b8480e92069c3 doesn't fix the problem for me. You also need to check for EACCES. See https://github.com/NLnetLabs/unbound/commit/40fbc3fa8a802dc3d9f12ee6db8b8480e92069c3#r54645670

**Comment by wcawijngaards** [comment]
Thanks for the report, fixed to ignore those printouts at low verbosity too, in https://github.com/NLnetLabs/unbound/commit/ad45e9b89ee18bbfeff0ed45da2c243ac17acfe6
