### ISSUE TITLE
Unbound cannot establish a chain of trust to keys for .sx domains

### ISSUE THREAD

**Issue by tr0ner** [NLnetLabs/unbound#539]
Unbound seems to have problems with all .sx domains and returns a servfail. 
Example domains:
whois.sx
registry.sx
It looks like it does not like the dnskeys.
More info can be found here:
https://dietpi.com/phpbb/viewtopic.php?f=11&t=9399

**System:**
 - Unbound version:  1.13.1
 - OS: DietPi
 - `unbound -V` output:
Configure line: --build=arm-linux-gnueabihf --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules --libdir=${prefix}/lib/arm-linux-gnueabihf --libexecdir=${prefix}/lib/arm-linux-gnueabihf --disable-maintainer-mode --disable-dependency-tracking --disable-rpath --with-pidfile=/run/unbound.pid --with-rootkey-file=/var/lib/unbound/root.key --with-libevent --with-pythonmodule --enable-subnet --enable-dnstap --enable-systemd --with-chroot-dir= --with-dnstap-socket-path=/run/dnstap.sock --libdir=/usr/lib --disable-flto
Linked libs: libevent 2.1.12-stable (it uses epoll), OpenSSL 1.1.1k  25 Mar 2021
Linked modules: dns64 python subnetcache respip validator iterator

BSD licensed, see LICENSE in source package for details.

**Comment by gthess** [comment]
Hi!
It seems that this is resolved ATM (signing on the .sx TLD that is).
At least I don't see a problem now. Could you verify?
I see that they had some problems in the past (https://dnsviz.net/d/whois.sx/YTFJuA/dnssec/) (this is roughly 2 months ago), maybe they are trying different DNSSEC configurations? And then maybe you happened to ask on the day that it was really broken?

**Comment by tr0ner** [comment]
Thank you for coming back to me. For me it still does not resolve .sx domains.

**Comment by gthess** [comment]
I don't see problems with Unbound or with other open resolvers. I suspect it is something in your setup or network.

First off restart Unbound to make sure cached records don't interfere with testing. Then you can try:
- `dig @unbound whois.sx`; I assume this returns SERVFAIL as you said;
- `dig @unbound whois.sx +cd`; this would return the answer if DNSSEC was the issue;

If that is the case you can use `val-log-level: 2` in the configuration file to have the validator log the DNSSEC failures and try again. You can set `verbosity: 0` to only get the validator's logs but `verbosity: 2`may give more information on the actual traffic.

Could you also share your configuration?

**Comment by Joulinar** [comment]
Hi,

let me step in 😃 

Today I did a test with our DietPi unbound installation and domain `registry.sx` + `whois.sx` succeed ootb. Test result I stored on our forum https://dietpi.com/phpbb/viewtopic.php?p=38999#p38999

Our `unbound.conf` is available on GitHub https://github.com/MichaIng/DietPi/blob/master/.conf/dps_182/unbound.conf

**Comment by tr0ner** [comment]
I tried again too today and it seems to be working fine now. Maybe it was a cache thing indeed.
